/*
 * bin2rope: convert a yaYUL .bin file into a C array suitable for embedding
 * in the N64 ROM as src/rope.c. Runs on the host (not the N64).
 *
 * Usage:
 *   tools/bin2rope path/to/Luminary099.bin > src/rope.c
 *
 * Output mirrors the rope.h declaration:
 *   const unsigned char CoreRope[CORE_SIZE][2] = { {hi,lo}, {hi,lo}, ... };
 *
 * Input format (per Virtual AGC convention):
 *   Big-endian 16-bit words, 15 bits of data + 1 bit of (odd) parity in the
 *   LSB. Banks appear in the order 2,3,0,1,4,5,...,35 - bin2rope does NOT
 *   reorder; agc_host_init does that at boot.
 *
 * The expected file size is exactly 044 * 02000 * 2 = 73728 bytes. The tool
 * refuses to write a file that doesn't match.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define CORE_SIZE (044 * 02000)
#define EXPECTED_BYTES (CORE_SIZE * 2)

int
main(int argc, char **argv)
{
  if (argc != 2) {
    fprintf(stderr, "usage: bin2rope <Luminary099.bin>\n");
    return 2;
  }

  FILE *f = fopen(argv[1], "rb");
  if (!f) {
    perror(argv[1]);
    return 1;
  }
  fseek(f, 0, SEEK_END);
  long size = ftell(f);
  rewind(f);
  if (size != EXPECTED_BYTES) {
    fprintf(stderr,
            "bin2rope: %s is %ld bytes, expected %d. "
            "Was yaYUL invoked with the right options?\n",
            argv[1], size, EXPECTED_BYTES);
    fclose(f);
    return 1;
  }

  unsigned char *buf = malloc(EXPECTED_BYTES);
  if (!buf) { fclose(f); return 1; }
  if (fread(buf, 1, EXPECTED_BYTES, f) != EXPECTED_BYTES) {
    perror(argv[1]);
    free(buf);
    fclose(f);
    return 1;
  }
  fclose(f);

  printf("/* Auto-generated by tools/bin2rope from %s. Do not edit. */\n",
         argv[1]);
  printf("#include \"rope.h\"\n\n");
  printf("const unsigned char CoreRope[CORE_SIZE][2] = {\n");
  for (long i = 0; i < CORE_SIZE; i++) {
    if ((i & 7) == 0) printf("  ");
    printf("{0x%02x,0x%02x},", buf[i*2], buf[i*2 + 1]);
    if ((i & 7) == 7) printf("\n");
    else              printf(" ");
  }
  printf("};\n");

  free(buf);
  return 0;
}
